version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/sidecar"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      sidecar-deps:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/sidecar"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
